# Generated by Django 5.2 on 2025-06-05 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_playermatchstats'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playermatchstats',
            unique_together={('match', 'player')},
        ),
    ]
